---
title: "Subject_Analysis"
output: html_document
---

Load up the data

```{r set up libraries}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r helper functions}
  lagpad <- function(x, k) {
    if(k > 0) {
      c(rep(NA, k), x)[1 : length(x)] 
    } else {
      c(x, rep(NA, abs(k)))[abs(k)+1 : length(x)]
    }}
```

```{r load data}
  m_data = read.csv("../Data/model_simulation.csv")

  ## Get indices of columns to convert
  ii <- grep(glob2rx("*_choice"), names(m_data))
  
  ## Convert and replace the indicated columns
  m_data[ii] <- lapply(m_data[ii], as.factor)
  m_data$context = round(m_data$context,1)
  m_data$ts = as.factor(m_data$ts)
  m_data$last_ts = as.factor(lagpad(m_data$ts,1))
```

```{r logistic regression}
  glm_optimal = glm(optimal_noisy_choice ~ context + last_ts, family = binomial, data = m_data)
  summary(glm_optimal)
  glm_ignore = glm(ignore_noisy_choice ~ context + last_ts, family = binomial, data = m_data)
  summary(glm_ignore)
  glm_single = glm(single_noisy_choice ~ context + last_ts, family = binomial, data = m_data)
  summary(glm_single)


  glm_all = glm(single_noisy_choice ~ optimal + single + ignore, family = binomial, data = m_data)

  
```


```{r convert to long form}
  m_long = select(m_data,-contains('choice')) %>%
      gather('model','conf',matches('ignore*|single*|optimal*'))
  m_long$choice = as.factor(round(m_long$conf))
  noisy_rows = grep("noisy",m_long$model)
  m_noisy_long = m_long[noisy_rows,]
  m_long = m_long[-noisy_rows,]
  
```

```{r }
ggplot(data = m_long, aes(context, conf, color = last_ts)) +
  geom_point(aes(alpha = .001), position = 'jitter') + geom_smooth() +
  facet_grid(model~.)

```
